service: ai4e-lambda-c03

frameworkVersion: "3"

package:
  exclude:
    - node_modules/**
    - README.md
    - package.json
    - package-lock.json
    - buildspec.yaml
    - bitbucket-pipelines.yml

plugins:
  - serverless-python-requirements
  - serverless-deployment-bucket

custom:
  basePath: src
  region: ap-southeast-1
  prefix: lbd-func
  pythonRequirements:
    layer: true

provider:
  name: aws
  runtime: python3.8
  region: ap-southeast-1
  memorySize: 128
  timeout: 300
  deploymentBucket:
    name: ${env:LAMBDA_DEPLOYMENT_BUCKET_NAME}
    maxPreviousDeploymentArtifacts: 10
    blockPublicAccess: true
    skipPolicySetup: true
    versioning: true
    serverSideEncryption: AES256

functions:
  - ${file(./src/ai4e_crawler/sub_serverless.yml)}
  - ${file(./src/thiemcun203/sub_serverless.yml)}
  - ${file(./src/namtran204/sub_serverless.yml)}
  - ${file(./src/huynhduc123/sub_serverless.yml)}
  - ${file(./src/nhatminh46vn/sub_serverless.yml)}
  - ${file(./src/nducloc02/sub_serverless.yml)}
  - ${file(./src/hieund3579/sub_serverless.yml)}
  - ${file(./src/trangnv/sub_serverless.yml)}
  - ${file(./src/tientran082614/sub_serverless.yml)}
  - ${file(./src/dunj1710/sub_serverless.yml)}
  - ${file(./src/phuonganh180402/sub_serverless.yml)}
  - ${file(./src/hnaw257/sub_serverless.yml)}
  - ${file(./src/tinhnguyen1011/sub_serverless.yml)}
  - ${file(./src/dungpnt1998/sub_serverless.yml)}
  - ${file(./src/chanpttt1010/sub_serverless.yml)}
  - ${file(./src/syun1208/sub_serverless.yml)}
  - ${file(./src/thynhalam919/sub_serverless.yml)}
  - ${file(./src/taivlc1182/sub_serverless.yml)}
  - ${file(./src/tris0410/sub_serverless.yml)}
  - ${file(./src/tnva1802/sub_serverless.yml)}

